#!/bin/bash

set -e

not_installed() {
  ! command -v $1 > /dev/null 2>&1
}

porter_dir=$(cd $(dirname $0)/.. && pwd)

if not_installed ginkgo; then
  echo "# ginkgo is not installed! installing it now....."
  go install github.com/onsi/ginkgo/ginkgo
fi

cd $porter_dir

ginkgo -r -p .