groups: []
resources:
- name: porter-image-dev
  type: docker-image
  source:
    password: ((docker.password))
    repository: concourse/porter-dev
    tag: dev
    username: ((docker.username))
  icon: docker
- name: porter-image-passed
  type: docker-image
  source:
    password: ((docker.password))
    repository: concourse/porter-dev
    tag: passed
    username: ((docker.username))
  icon: docker
- name: porter-repo
  type: git
  source:
    branch: master
    private_key: ((concourse_bot_private_key))
    uri: git@github.com:concourse/porter
  icon: github-circle
- name: ubuntu-bionic
  type: docker-image
  source:
    repository: ubuntu
    tag: bionic
  icon: docker
- name: version
  type: semver
  source:
    branch: version
    driver: git
    file: version
    private_key: ((concourse_bot_private_key))
    uri: git@github.com:concourse/porter
  icon: tag
- name: kind-release
  type: github-release
  source:
    owner: kubernetes-sigs
    repository: kind
    access_token: ((concourse_github_dummy.access_token))
    pre_release: true
- name: kind-on-c
  type: git
  source:
    uri: https://github.com/pivotal-k8s/kind-on-c
resource_types:
- name: docker-image
  type: registry-image
  source:
    repository: concourse/docker-image-resource
  privileged: true


jobs:
- name: build-ubuntu
  plan:
  - in_parallel:
      steps:
      - get: porter-repo
        trigger: true
      - get: ubuntu-bionic
        trigger: true
        params:
          save: true
  - put: porter-image-dev
    params:
      build: porter-repo
      dockerfile: porter-repo/Dockerfile
      load_base: ubuntu-bionic


- name: integration-test
  plan:
  - get: porter-repo
    passed:
    - build-ubuntu
  - task: run-tests
    privileged: true
    file: porter-repo/ci/tasks/integration-test.yaml
    params:
      GCP_SERVICE_KEY: ((gcp_service_key))
- name: publish-major
  plan:
  - in_parallel:
      steps:
      - get: porter-repo
        passed:
        - integration-test
      - get: porter-image-dev
        params:
          save: true
      - get: version
        params:
          bump: major
  - put: porter-image-passed
    params:
      load: porter-image-dev
  - put: version
    params:
      file: version/version
- name: publish-minor
  plan:
  - in_parallel:
      steps:
      - get: porter-repo
        passed:
        - integration-test
      - get: porter-image-dev
        params:
          save: true
      - get: version
        params:
          bump: minor
  - put: porter-image-passed
    params:
      load: porter-image-dev
  - put: version
    params:
      file: version/version
- name: publish-patch
  plan:
  - in_parallel:
      steps:
      - get: porter-repo
        passed:
        - integration-test
      - get: porter-image-dev
        params:
          save: true
      - get: version
        params:
          bump: patch
    image: porter-image-dev
  - put: porter-image-passed
    params:
      load: porter-image-dev
  - put: version
    params:
      file: version/version
