apiVersion: v1
kind: Pod
metadata:
  name: gcp-push-pod
spec:  # specification of the pod's contents
  restartPolicy: Never
  containers:
    - name: hello
      image: busybox
      command: ['sh', '-c', 'echo Hello Concourse > /workspace/hello']
      volumeMounts:
        - name: workspace
          mountPath: "/workspace"
    - name: output
      imagePullPolicy: Always
      image: concourse/porter-dev:dev
      command: ["/opt/porter/out/outputs"]
      args: ["--source-path", "/workspace", "--bucket-url", "gs://porter-dev-bucket", "--destination-path", "out.tar" , "--pod-name", "gcp-push-pod", "--container-name", "hello"]
      volumeMounts:
        - name: workspace
          mountPath: "/workspace"
        - name: secret
          mountPath: "/secret"
          readOnly: true
      env:
        - name: "GOOGLE_APPLICATION_CREDENTIALS"
          value: "/secret/gcp-service-key"
  volumes:
    - name: workspace
      emptyDir: {}
    - name: secret
      secret:
        secretName: gcp-secrets