apiVersion: v1
kind: Pod
metadata:
  name: gcp-pull-pod
spec:
  restartPolicy: Never
  containers:
    - name: input
      image: concourse/porter-dev:dev
      imagePullPolicy: Always
      command: ["/opt/porter/in/inputs"]
      args: ["--source-path", "out.tar", "--bucket-url", "gs://porter-dev-bucket", "--destination-path", "/" ]
      volumeMounts:
        - name: workspace
          mountPath: "/workspace"
        - name: secret
          mountPath: "/secret"
          readOnly: true
      env:
        - name: "GOOGLE_APPLICATION_CREDENTIALS"
          value: "/secret/gcp-service-key"
    - name: hello
      image: busybox
      command: ['ls', '-c', '/workspace/hello']
      volumeMounts:
        - name: workspace
          mountPath: "/workspace"
  volumes:
    - name: workspace
      emptyDir: {}
    - name: secret
      secret:
        secretName: gcp-secrets